### ISSUE TITLE
路由切换的时候页面会闪动一下

### ISSUE THREAD

**Issue by ArriveAstral** [midfar/vue3-element-admin#3]
就是切换路由比如点击tabs标签页，页面会闪一下，像刷新了一样

**Comment by ArriveAstral** [comment]
是啥原因，是需要什么配置吗？

**Comment by ArriveAstral** [comment]
加载过的页面路由第二次就不会在闪了，第一就会闪

**Comment by ArriveAstral** [comment]
我感觉是那个keep-alive问题，我把keep-alive给删了测试了几遍好像没有这个问题了

**Comment by ArriveAstral** [comment]
给了路由 path全路径 就不闪了

**Comment by midfar** [comment]
好像只开发模式才有问题吧？打包后貌似没问题，可以给vue-router提bug
